#!/bin/sh
#
#BATCH --job-name=aircrafts-15_mvcnn_3334_2_vgg16_%a
#SBATCH --array=1-5
#SBATCH -o '/mnt/nfs/scratch1/gperezsarabi/Multispectral_domain_adaptation/logs/aircrafts/aircrafts-15_mvcnn_3334_2_vgg16_%a.txt'
#SBATCH --partition=m40-long
#SBATCH --gres=gpu:1
#SBATCH --mem=24GB

source activate envpy3

python src/train.py \
	--array $SLURM_ARRAY_TASK_ID \
	--batch-size 64 \
        --epochs 30 \
        --lr 1e-4 \
        --model none \
        --backbone vgg16 \
        --pretrained_adaptor 0 \
        --inflate 0 \
	--num_views 2 \
        --channels 15 \
        --dataset aircrafts \
        --numdata 3334 \
	
